server:
    port: 8001
spring:
    application:
        name: client-4
    cloud:
        consul:
            discovery:
                instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#                service-name: ${spring.application.name}
#                health-check-critical-timeout: 30s
                healthCheckInterval: 15s
                health-check-path: /actuator/health
#                health-check-url: 192.168.55.89/actuator/health
            host: 123.57.101.34
            port: 8500
