server:
    port: 8001
spring:
    application:
        name: client-5
    cloud:
        consul:
            discovery:
                register: true
                prefer-ip-address: true
                instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#                service-name: ${spring.application.name}
#                port: ${server.port}
            host: 123.57.101.34
            port: 8500
